services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB:  ${DB_NAME}
    ports:
      - "5432:${DB_PORT}"
    volumes:
      - ./internal/repository/migrations:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:${APP_PORT}"
    environment:
      APP_PORT: ${APP_PORT}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: ${DB_SSLMODE}
      LOGGER_LEVEL: ${LOGGER_LEVEL}
      LOG_FORMAT: ${LOG_FORMAT}

volumes:
  postgres_data: